export const  USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const  USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_ERROR = 'USER_REGISTER_ERROR';


export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';


export const ERROR_OCCURED = 'ERROR_OCCURED';


export const LOGOUT_USER_REQUEST = 'LOGOUT_USER_REQUEST';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_ERROR = 'LOGOUT_USER_ERROR';

export const GET_TWEETLIST_REQUEST = 'GET_TWEETLIST_REQUEST';
export const GET_TWEETLIST_ERROR = 'GET_TWEETLIST_ERROR';
export const GET_TWEETLIST_SUCCESS = 'GET_TWEETLIST_SUCCESS';

export const ADD_TWEETLIST_REQUEST = 'ADD_TWEETLIST_REQUEST';
export const ADD_TWEETLIST_ERROR = 'ADD_TWEETLIST_ERROR';
export const ADD_TWEETLIST_SUCCESS = 'ADD_TWEETLIST_SUCCESS';

 